version: 0.2

env:
  variables:
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPOSITORY
  build:
    commands:
      - pwd
      - ls -lstr
      - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
  post_build:
    commands:
      - docker push $ECR_REPOSITORY:latestredis

artifacts:
  files:
    - imagedefinitions.json